In [6]:
import numpy as np

In [3]:
#Creating an Array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
# 0-D array
arr0 = np.array(80)
arr0

array(80)

In [10]:
#check dimension of array
print(arr0.ndim)
arr.ndim

0


1

In [24]:
#2-D array
arr2 = np.array([[1,2,3,4,5],[10,20,8,9,7]])
arr2

array([[ 1,  2,  3,  4,  5],
       [10, 20,  8,  9,  7]])

In [17]:
#Find total numbers of elements
arr2.size

10

In [8]:
#Total memory size taken by an array
arr2.nbytes

80

In [19]:
arr0.nbytes

8

In [25]:
#Single element size
'''
[[ 1,  2,  3,  4,  5],
[10, 20,  8,  9,  7]]
'''
arr2.itemsize

8

In [25]:
#Data type of array
arr2.dtype

dtype('int64')

In [26]:
print(arr2)

[[ 1  2  3  4  5]
 [10 20  8  9  7]]


In [11]:
#Specific element of the array()
arr2[1,3]

np.int64(9)

In [13]:
#find specific row from the array
arr2[0,:]

array([1, 2, 3, 4, 5])

In [14]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
#(Start Index:Ending Index)[inclusive:exclusive]
arr3[1:5]

array([2, 3, 4, 5])

In [17]:
arr3[5:]

array([ 6,  7,  8,  9, 10])

In [18]:
arr3[:5]

array([1, 2, 3, 4, 5])

In [19]:
print(arr2)

[[ 1  2  3  4  5]
 [10 20  8  9  7]]


In [21]:
print(arr2[1,1:4])

[20  8  9]


In [22]:
#Copying an array
arr4 = arr2.copy()
print(arr4)

[[ 1  2  3  4  5]
 [10 20  8  9  7]]


In [23]:
#Zero Matrix
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# 1 Matrix
np.ones((6,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
#Other Matrix
np.full((4,4),45)

array([[45, 45, 45, 45],
       [45, 45, 45, 45],
       [45, 45, 45, 45],
       [45, 45, 45, 45]])

In [1]:
#import random
from numpy import random

In [2]:
x = random.randint(100)
print(x)

82


In [8]:
np.random.rand(2,4)

array([[0.9273452 , 0.3780833 , 0.72859926, 0.56208906],
       [0.88211727, 0.52659016, 0.37251348, 0.26085586]])

In [9]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
#Mathematical Operation on array
arrm = np.array([10,0,0,40])
print(arrm)

[10  0  0 40]


In [11]:
#Plus operation
arrm = arrm+10
print(arrm)

[20 10 10 50]


In [14]:
#Substraction
arrm = arrm-10
print(arrm)

[  0 -10 -10  30]


In [16]:
#Multiplication
print(arrm)
arrm*2

[  0 -10 -10  30]


array([  0, -20, -20,  60])

In [17]:
#Division
arrm/7

array([ 0.        , -1.42857143, -1.42857143,  4.28571429])

In [19]:
#Addition of 2 Arrays
a1 = np.array([10,15,30,40])
a2 = np.array([2,5,5,4])
print(a1+a2)

[12 20 35 44]


In [20]:
#Cos function in an array
np.cos(a1)

array([-0.83907153, -0.75968791,  0.15425145, -0.66693806])

In [27]:
#Find minimum/maximum value in an array
print(arr2)

[[ 1  2  3  4  5]
 [10 20  8  9  7]]


In [29]:
np.min(arr2)
np.max(arr2)

np.int64(20)

In [30]:
np.sum(arr2)

np.int64(69)

In [31]:
#iterating in 1-D
for x in a1:
    print(x)

10
15
30
40


In [32]:
#iterating in 2-D
for z in arr2:
    print(z)

[1 2 3 4 5]
[10 20  8  9  7]


In [33]:
for a in arr2:
    for b in a:
        print(b)

1
2
3
4
5
10
20
8
9
7
